baseURL = "https://bunnyislewd.com/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"

title = "Bunnyislewd adult online content creator"
# copyright = "Copy, _right?_ :thinking_face:"
description = "Bunnyislewd is a shy, naughty, sexually open-minded LGBTQ+ adult content creator."
keywords = [
    "bunnyislewd",
    "bunny xxx",
    "adult content creator",
    "18+",
    "tits",
    "petite",
    "small tits",
    "small boobs",
    "boobs",
    "emo",
]

enableEmoji = true
disableKinds = ["taxonomy", "term"]
favicon = false
#favicon = "favicon.ico"

[params.author]
name = "Bunnyislewd"
headline = "18+ camgirl and adult content creator"
#image = "images/frontal.jpg"                       # path relative to static directory
#image = "https://site-files.dftba.xyz/bunnyislewd/frontal.jpg"
image = "/android-chrome-512x512.png"

links = [
    { link = { href = "https://cash.app/$BunnyisLewd", text = "Cashapp", icon = "cashapp" } },
    { link = { href = "https://chaturbate.com/bunnyislewd", text = "Chaturbate" } },
    { link = { href = "https://onlyfans.com/bunnyislewd", text = "Onlyfans", icon = "onlyfans" } },
    { link = { href = "https://fansly.com/bunnyislewd", text = "Fansly" } },
    { snapchat = "https://snapchat.com/add/bunnyislewd" },
    { twitter = { href = "https://x.com/bunnyisnude", text = "Private Twitter ($15 via Cashapp)", icon = "twitter" } },
    { twitter = { href = "https://x.com/bunnyislewd", text = "Public Twitter", icon = "twitter" } },
    { bluesky = "https://bsky.app/profile/bunnyislewd.bsky.social" },

    { amazon = { href = "https://www.pornhub.com/model/bunnyislewd", text = "Pornhub", icon = "link" } },
    { link = { href = "https://www.manyvids.com/Feed/bunnyislewd/1003105966", text = "Manyvids", icon = "" } },
    { link = { href = "https://stripchat.com/bunnyislewd", text = "Stripchat", icon = "link" } },
    { link = { href = "https://www.sextpanther.com/bunnyislewd", text = "Sextpanther", icon = "link" } },

    { link = { href = "https://throne.com/bunnyislewd", text = "Throne Wishlist", icon = "gift" } },
    { amazon = { href = "https://www.amazon.com/hz/wishlist/ls/3R9Y9JHL2K0QD", text = "Stream room renovations/recovery wishlist", icon = "gift" } },
    { amazon = "https://www.amazon.com/hz/wishlist/ls/BK7MD246AJAV" },

    { twitch = "https://twitch.tv/bunnyisgaming" },
    { email = "mailto:bunnyislewd@outlook.com" },
    { link = { href = "https://linktr.ee/Bunnyislewd", text = "Linktree" } },

    # { link = "https://link-to-some-website.com/" },

    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "" },
    # { gitlab = "" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "" },
    # { mastodon = "" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },

    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "" },
    # { tumblr = "https://username.tumblr.com" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "" },
    # { youtube = "" },

] #  { link = { href = "https://github.com/jpanther/lynx/blob/stable/README.md", text = "View the readme", icon = "github" } },
#  { link = { href = "styles/", text = "All the link styles", target = "_self" } },

[module]
[module.hugoVersion]
extended = false
min = "0.86.1"
